- name: Install updates
  hosts: all
  become: true
  become_method: doas
  gather_facts: true
  tasks:
    - name: Install updates
      community.general.apk:
        update_cache: true
        upgrade: true